### ISSUE TITLE
test_process() fails on some runs

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-gnn-2#47]
The `test_process()` test fails on some runs (but also sometimes succeeds). Maybe there is some undeterministic about the function that it tests?

Here is the failing test report: 
```
    def test_preprocess():
    
        output_directory = mkdtemp()
    
        prefix = os.path.join(output_directory, "test-preprocess")
    
        preprocessor = PreProcessor(prefix)
        try:
            preprocessor.start()
    
            count_queries = 100
            for number in range(1, count_queries + 1):
                query = SingleResidueVariantResidueQuery("tests/data/pdb/101M/101M.pdb", "A", number, None,
                                                         alanine, phenylalanine,
                                                         pssm_paths={"A": "tests/data/pssm/101M/101M.A.pdb.pssm"},
                                                         variant_conservation=0.0, wildtype_conservation=0.0)
                preprocessor.add_query(query)
    
            preprocessor.wait()
    
            assert len(preprocessor.output_paths) > 0
    
            count_graphs = 0
            for path in preprocessor.output_paths:
                with h5py.File(path, 'r') as f5:
                    count_graphs += len(f5.keys())
    
>           assert count_queries == count_graphs, f"{count_queries} != {count_graphs}"
E           AssertionError: 100 != 1
E           assert 100 == 1

tests/test_preprocess.py:39: AssertionError
```
If I test locally the values for `count_graphs` are different every run, usually around 80 (and sometimes 100 if the test succeeds).

See also [this test run](https://github.com/DeepRank/deeprank-gnn-2/runs/5722662920?check_suite_focus=true)

**Comment by svenvanderburg** [comment]
This was (probably) fixed with https://github.com/DeepRank/deeprank-gnn-2/commit/67469eee2fd0e8d7fb8f91c7f41b5b594a870172#

```python
while not self._input_queue.empty():
```
was changed to
```python
while self._input_queue.qsize() > 0: # qsize seems to be more reliable than the empty method
```

However, the `Queue.qsize()` method is not supported on Mac OS X (and also other Unix platforms). From what I get from the documentation, it is also not 100% reliable for checking whether the queue is empty.

**Comment by svenvanderburg** [comment]
@cbaakman can you confirm that you fixed this? (on your platform at least 😋 )

**Comment by cbaakman** [comment]
> @cbaakman can you confirm that you fixed this? (on your platform at least yum ) Then close the issue.

Yes. It worked on my platform. After my last commit.

**Comment by svenvanderburg** [comment]
Check
