### ISSUE TITLE
Investigate using external dependency for forcefield calculations

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-gnn-2#50]
We implement our own forcefield calculations, for example:
coulomb potential: https://github.com/DeepRank/deeprank-gnn-2/blob/f9c50a9055b01c2ff622319b513290a41e45bf0f/deeprank_gnn/models/query.py#L603 and vanderwaals potential: https://github.com/DeepRank/deeprank-gnn-2/blob/f9c50a9055b01c2ff622319b513290a41e45bf0f/deeprank_gnn/models/query.py#L634 

Investigate whether we can use a mature external dependency (such as biopython) for these kind of calculations. Then we don't have to maintain this part of the code, the implementations might be faster, and we avoid the risk of errors popping up if anyone changes the code.

If a nice alternative is found, create a new issue for replacing our own code with the dependency.

**Comment by cbaakman** [comment]
Depending on the type of forcefield, we might need structures with hydrogens in them. This can be a problem, because most X-ray structures don't contain those. We have been experimenting with reduce to add them: https://github.com/rlabduke/reduce
Using reduce would mean that we have to give those developers credit in our publications.

**Comment by rgayatri** [comment]
I checked with other forcefield libraries on github/biopython, but these are not optimized for amino-acids. We have CHARMM, AMBER and GROMACS forcefields that are widely used for molecular dynamics simulations. Li discussed on having these integrated in future (for other projects).
Haddock software uses an in-house version of OPLS, and I think the authors of deeprank used the same.
It might be better to stick with current version.
