### ISSUE TITLE
Investigate using external dependency for mapping graph to grid

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-gnn-2#51]
We implement our own methods for mapping a graph to a 3D grid, see for example:
https://github.com/DeepRank/deeprank-gnn-2/blob/67469eee2fd0e8d7fb8f91c7f41b5b594a870172/deeprank_gnn/models/grid.py#L166
and 
https://github.com/DeepRank/deeprank-gnn-2/blob/67469eee2fd0e8d7fb8f91c7f41b5b594a870172/deeprank_gnn/models/grid.py#L141.

Investigate whether we can use a mature external dependency for these kind of calculations. Then we don't have to maintain this part of the code, the implementations might be faster, and we avoid the risk of errors popping up if anyone changes the code.

If a nice alternative is found, create a new issue for replacing our own code with the dependency.

**Comment by rgayatri** [comment]
I do find some external libraries:
https://paperswithcode.com/task/3d-point-cloud-classification
https://www.researchgate.net/publication/325189340_Large-scale_3D_Point_Cloud_Classification_Based_On_Feature_Description_Matrix_By_CNN

I think tailoring any of the above for deeprank could take a while. 
We do not find substantial difference in performance or speed between fast-guassian and nearest-neighbour implementations. 
I suppose we could choose to retain existing libraries until a change is deemed necessary.
