### ISSUE TITLE
Implement QueryDataset class

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-gnn-2#53]
Description still needs to be added.

**Comment by cbaakman** [comment]
I believe we do have this class here: https://github.com/DeepRank/deeprank-gnn-2/blob/037c8fd0f72cdbc1d2da85b17e75b2cbb574bced/deeprank_gnn/models/query.py#L451

**Comment by gcroci2** [comment]
> I believe we do have this class here:
> 
> https://github.com/DeepRank/deeprank-gnn-2/blob/037c8fd0f72cdbc1d2da85b17e75b2cbb574bced/deeprank_gnn/models/query.py#L451

Do we need to add functionalities or is it okay as it is now?
