### ISSUE TITLE
Replace multiprocessing.Queue with multiprocessing.pool.map in PreProcessor

### ISSUE THREAD

**Issue by svenvanderburg** [DeepRank/deeprank-gnn-2#56]
The `PreProcessor` class currently uses a quite low-level combination of `multiprocessing.Process` and `multiprocessing.Queue` to parallelise graph construction from .pdb files based on queries.

See https://github.com/DeepRank/deeprank-gnn-2/blob/c0bff28d73bf67a14fd4f55d9adac5884a2dde1a/deeprank_gnn/preprocess.py#L73

From what I understand, we don't really need queues. This is more a map-type problem. Because we always just have a list of queries we want to send at once to the preprocessor, and then just want to collect the results. (for example we are not polling from another process and then adding to the queue).

I suggest to refactor `Preprocessor` so that it makes use of `multiprocessing.pool.map` instead. Benefits:
* More high-level, code will be simplified a lot
* We don't have to worry about the different processes itself, that is all handled for us.
* This will also solve #55, and guarantees to solve the problem that arose in #47 and was presumably fixed with using `Queue.qsize()`. (i.e. checking whether the process is done is handled by `pool.map` itself)

**Comment by svenvanderburg** [comment]
@cbaakman can you comment on whether you think this is a good idea? (or maybe we can discuss)

**Comment by cbaakman** [comment]
It's a good idea to use a pool. But I don't have experience with that. It doesn't seem to have priority to me, if the current approach works as well.
