### ISSUE TITLE
Allow passing our own train/test/split to deeprank-gnn-2 NeuralNet

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-gnn-2#81]
If we want to create our own train/test/validation split, for example according to peptide clusters, starting from the complete .hdf5 files, how can we use NeuralNet class?

**Comment by cbaakman** [comment]
NeuralNet has the percent setting, which can be used to divide the dataset into train and validation: https://github.com/DeepRank/deeprank-gnn-2/blob/9f668f2aaa06e9c8fb8ff954ef5f4b5d21dc073d/deeprank_gnn/NeuralNet.py#L193

We could expand this to testing

**Comment by gcroci2** [comment]
> 

We've seen that setting, but we would need to split the data according to peptide clusters (not randomly), and this complicates things a bit. I think that it would be ideal to have the possibility to implement our own splitting (also for a future user). As it is now, I think it's a bit too much hardcoded. Ideally, it would be nice to pass the customized DataSet to the NeuralNet class, making it less hardcoded and more customizable.

**Comment by gcroci2** [comment]
I am implementing this in the PR #85 (issue #83)

**Comment by gcroci2** [comment]
We want to add one more step: the split of the dataset should be performed out of the NeuralNet class, after the instantiation of the HDF5DataSet object.
