### ISSUE TITLE
Use customized HDF5DataSet class

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-gnn-2#83]
When we use NeuralNet class, the first parameter is the path of the .hdf5 files, and this works well if we don't need to modify anything about them. But what if I'd like to customize the HDF5DataSet class, for example using either a transform or a pre-transform? How can I pass the "customized" HDF5DataSet object to the NeuralNet class?

**Comment by cbaakman** [comment]
I don't think the original authors of deeprank made the option for this. But I think it can be done by setting the NeuralNet.train_loader variable to a torch_geomatric.data.DataLoader object, that holds your custom HDF5DataSet object.

**Comment by gcroci2** [comment]
From the original deeprank:

```
# declare the dataset instance
data_set = DataSet(database,
            chain1='C',
            chain2='D',
            grid_info={
                'number_of_points': (10, 10, 10),
                'resolution': (3, 3, 3)},
            select_feature={
                'AtomicDensities': {'C': 1.7, 'N': 1.55, 'O': 1.52, 'S': 1.8},
                'Features': ['coulomb', 'vdwaals', 'charge', 'PSSM_*']},
            select_target='DOCKQ',
            normalize_features = True, normalize_targets=True,
            pair_chain_feature=np.add,
            dict_filter={'DOCKQ':'<1'})


# create the network
model = NeuralNet(data_set,cnn_reg,model_type='3d',task='reg',
                  cuda=False,plot=True,outdir=out)

```

Here the DataSet class is used to generate the dataset object, and then NeuralNet takes it as input, not the database path. It would be super useful to have the same!

About the train_loader attribute, yes we could modify it, but still I think it's better to modify the code in order to have this possibility implemented in the NeuralNet parameters.
