### ISSUE TITLE
Add unit tests for NeuralNet class parameters

### ISSUE THREAD

**Issue by gcroci2** [DeepRank/deeprank-gnn-2#86]
Parameters in NeuralNet class for which we need either examples or unit tests:

 - [x] transform_sigmoid

Please add others if needed @DTRademaker

**Comment by cbaakman** [comment]
I added one unit test for transform_sigmoid here: https://github.com/DeepRank/deeprank-gnn-2/compare/main...neuralnet-param-tests

What other parameters shall we test?

**Comment by gcroci2** [comment]
> I added one unit test for transform_sigmoid here: [main...neuralnet-param-tests](https://github.com/DeepRank/deeprank-gnn-2/compare/main...neuralnet-param-tests)
> 
> What other parameters shall we test?

Thanks! For me the other parameters are okay. About transform_sigmoid, I am still missing its purpose (and it's not documented on NeuralNet.py, it should be added as well).
I mean, I read from the code that it's used only if the task is `reg` (regression), and it maps the predicted output to the [0,1] domain, but why (or when) would it be necessary?
